from typing import List

def count_nucleotides(dna: str) -> List[int]:
    counters = {}
    for symbol in dna:
        if symbol not in counters.keys():
            counters[symbol] = 0
        counters[symbol] += 1
    return [item[1] for item in sorted(counters.items())]

if __name__ == '__main__':
    dataset = 'ATCCATACAGAAATTTGCGCATTTCCTGTTAGTATACCTAATTTTCTAAAGAGCTTATGGGACAACCGTCGGCAGCCAAGGTATGCCCTCGCGTTAGCCGTACTATCACTTGGACCCCTGGTACCGCACCCCTTAAATCCTATTTTCATTTCACTTAGTCATACTGAATCCGATGACTCTATTGTGACGCGGCATTACGGTGGGTCGACCACAATTGGGTTACCCCGCTAACGCAAGCTAAAGCATAACTGATACTCGGCACTTAGCAACTAGTGTGGGTAAATCGCTAGCAGGCTCGGTTTGTAGCAAAGGCGGGCCAAGCGTCCCCAAAAGTGTTATATTCGTATCAGCTATCTAGCCTGTTTCAACTACAGGCTGAGTTGAAGAGACATATACCCACGGCGGGCTAGCCCATCACAAAGTAACTGAATGAAATTGGACGATTATGCGTAGCTATATTGAGGCCTCTCCTAGTATCGCGCAGTACTCTGCCGACATCAAAACATGAGGTCGTCTCGTGAAATTTATTTTTCTGCTCCTAGGTCAAGATCGCCGGATTGGTGGGGACCTCCAGCTATGGGAGGGCGGCTATCATCTTCTTCCTATCGCGCCCGGGGTACCCTGGGACGAATGCTAGTACTAACGCGATTAACTTCATTGATGCTTCTGACTGCGTGCAATGCATGCCGGGTATGGGCAAGTTTTAGCAATTCAGACACAGCTGTGGGTAGACGGCAGGTTACTCACGGTCCTCTGGTCGGTTGGTATTGTTTAGTCTGTAGAGGATTACATTAGCAGCGAGCACGCAACGGAGCACCGCATCAGAGACCCTATAGAAGCGATCGTCGAGCGAAGCTACACTGAATTGTCCACAAAGACTGCAACTACAAATGTCTATTCGTATTATCGTAACCAGCTGCGTGACTCGGTCTTTGCTTGTACACGGAAG'
    result = count_nucleotides(dataset)
    print(*result)