from typing import Dict, Tuple

def parse_fasta(fasta_data: str) -> Dict[str, str]:
    fasta_dict = {}
    strings = fasta_data.strip().split('>')
    
    for string in strings:
        
        if not string:
            continue

        elements = string.split()
        fasta_dict[elements[0]] = ''.join(elements[1:])
    
    return fasta_dict

def gc_content(dna: str) -> float:
    count = 0
    
    for symbol in dna:
        
        if symbol == 'G' or symbol == 'C':
            count += 1
    
    return 100 * count / len(dna)

def find_max_gc_content(fasta_data: str) -> Tuple[str, float]:
    fasta_dict = parse_fasta(fasta_data)
    
    max_gc_content = ('', 0.0)

    for label in fasta_dict:
        current_gc_content = (label, gc_content(fasta_dict[label]))
        
        if current_gc_content[1] > max_gc_content[1]:
            max_gc_content = current_gc_content
        
    return max_gc_content



if __name__ == '__main__':
    dataset = '''
    >Rosalind_1832
    TAGGATAACGCCATCGTCTAAACGGCCAGTCCCGTGCATTCGAAGGCTGTTGCGTATTTT
    TGATGTGAGATAAGGAAACCGCCCGAGGATTCATGCCGAAGGCTACTCAATCGTGGTGTA
    CACGGTCGTTTTCACCGTAAGTGCGAGCTCCATGTCTTGGATGACAAATCCTTTGTAGAT
    GTGACCCTGAAGTCACACAATCAGCAACGAGTACACACAGAGATAAGACAATGCATGCCT
    CTCTGCGGCGAAGCGTTTAAGTAAAATTATCTTAAAAATGAAGGCCCAGGCGTGCATCCT
    TCCAGAAGATTATGAACTAGAACGATGGAACCTGGCTTGCCCGAACGCTGCGCGATTTCG
    TCCATCATCCGCTAAACGAATCCCATATGGAGCGACCGAGTCCAGAGAATGCAGACCGAA
    GCGAATGGACATCCGCCACGAGACATAGTCCACTTAGTGGCTGCTAGGTCGAAAGAAACG
    GCGCAGGCGTAGATTTCGCTAGGCGCGGTTTTCAAAGGCCCTGTTTTCGAGGAGCCTATT
    ACGGCCTGGAGCTCCACGTTGGCTTTCCATGTGAGTCTGAGCAACAATTCGGCAATAATT
    CTAAGGAGGGGCAGAAGAGCCCTCACGCCTTTTAGAATTTCATTCGGGCAGCCCACCACT
    ATTCACCAGCCTTAGCACGAGCGGGGCGGAACTAACCCACGTTACGTAAACTTAGGCTCT
    TGGTGATCAAGTGGCCGCTCTAAGACTGCCGGGAACTCTCAATGTACACCGTTCAGGAAG
    GGCCCTAGTGCCCAATCGTTGAATTGGGAACAAAAAACTTAAATCCGGTGCATCAGAGAA
    CTATTTTCCTTGCCCGCAATCAACCTCTTTGACAGGGCATGTTCACTTGTAGGAGCAGAG
    CAACTTTACCTTCTTGATATTTTGGAGGAGAGTAATACA
    >Rosalind_8855
    CTGGATGAGTCGCGCCAGTTGCTTGACACCAGAAACGTCTCTGATTAACGGGGCCGCACC
    TCGATTTCTTGTCGATACCATGCGTGTTTGGCTTCTGTACGGAGAACGGGAAAGCAGTCG
    AACGCGTCCTACTCCATAGCGCGCCTAACACCTACATGTTGAATGAGCGACGCACGTCGC
    AGTATGCCAACTCGCCTGGTCACCCGACGGTCCGAGGAAATCGACGAACTCCAGATATAG
    ACTAGACGATTGCCTAATACACTTCGAACGTTATCCGTGTCGGCGTGGCATTAGATCGAT
    TGCTTCTGGCTCGACAACGCCGAATGACCGCGGGGTTCTGGCGATATTGGGGAAGGCTAA
    GCGGGTCACACGAGTCCGTTTATCGCACCAGAACTAGGACTGCTTCTTAGCATCCTTTAT
    ATCGATTCTACTTTCCCAATTTATACTCGCCACATGCGAGGCAATGGCACCTAACTCTTA
    CCTAGCCGGTATGAGTGACGATACGAGATACCGAGTCAAAAAGGACAATAGGATGTGCCG
    CCAAGCCTGGCGCGCTATGACGGAGTGGACGTATTAATGCTGCTTAGCGAGCGGTCCGTC
    ACGATCTGATGGCTATTGAAGTGTTTCGGGGCAAATACGGACCTACGCTTTGACTTTGTT
    GGCCAGGGTTCTTATCAGGACAGAAGTACAGCTGTGGCTACTTCTGCACTGATGCCTTGA
    GTAACGCATATTCGACAGGCGGCAACAGTAACCATGGATTATTCCGGCCGAAAATTTGGG
    CGTCTCATCCGCAAGTAACTCCTGGGGGCAAGCCAAGCGTACTTTAAAAGTATCTAGCCA
    CTGTACAGGTCGGTTGAAACTACGGTCCGGTTCAGTAGCACTCTCCGTAACTTTCGCAAC
    TTCGCTGGGATGTTAGTAAGCGTAGCTATTCAAATAGATTACGAGATCTGCAAAATAGAG
    TCAAACAGGGCTTGGAGACTCTTGGTTAAC
    >Rosalind_4004
    ATAGCAAATCGCGATTTGGCACGTGGCTCAAGTATCCATAGCCACAATGTACTGTTGAAA
    CTCAGCCGAAAGCTTACGACCAGAACCCGGTAGTGCAGATTAGGCTCGCTCGACTCGCGC
    CATGCCCGAGCCAGGCCCAGCTGCGGACCGGGATGCAGCATTTCTACGTTTTTTTTGTGT
    CGTTATAGCCTATCACCATCACAATTGTTTGTGCATGTACATAGTCCAGGACGTTGTGCT
    ACGTAACTCCGTTCGGACTGTGGTATGCGTCTGCACAAAGAGACTGACTAATCTTGTTCA
    TACCTACGGAGCCATAACTTGTAATAAGTTTTTATCGGTAATACTTTGTATGCTGGCGAT
    TTTACCTGCCTTGTTCCATGCTGAAGTGATGTCGATTTAAAACCGGGAGTAGGCGCTGGG
    TAGTTAGCTGAACATTTGAACGTTATGGTCGTGGGCTCATTTGCATTAGGCTCCCCTCTT
    TTCCATCTATATTCAGTTGGAATGATACCTAATGTCATACCGGGATGCGCCGGAACCACT
    ACGAGGGCAGTAATTAAAGTGGGCTTGCACGATCTTAGCGACTCAAGCGCGTGGTCAACA
    GAAATTCTGCCAGTCTGTCTGTGCGGACTGAGAGATTTGCACTACGACACTACCCATGTG
    GGGTTAACATAGGTCTTTATGGTATCTTTAGGATCTGCTTTGCGTCCAATACCGTCTGGC
    GAACAGGAAGATCTCGATGTATCCTGGCTGAGGATAGTCCCGCGGAGGAGCCTCCAAACT
    TGCAGCAGGGGTCTTGGCGGTAACGTCAGGGAAGCGTGGATCAACAACTTCAGTGGAATG
    CGCTCTTGAGCGACTATCAGTAATACCATTAATTGTTGGTCACAAGTTTGCGAAGATGGA
    TACTCTTCTTAGTGGGAACACTACCGAGTTCGACTGGTGTGTCCCTT
    >Rosalind_3218
    TATTGAAAACACTGTCAGCGATAAATTTCCACAGAAATGTGGTCTTCCAGTGAGCCGGCC
    AGCGTTCTTGCTCCGGATTAGGCAACTCGCAAGCCAGCTAGACATCAACGATTCGGTACG
    CATGGTATATCTTGTTATTCACGCAGGCTGTGGGAGGTGGATGCTTCATGCTTGAGATCT
    TATTTAACAAACTTTGGTTCTCGTAAGGAGCAGGATGTCCCACATCAAAACGCGCTAGCG
    CGGTTGCTTACTTAGCTTTGAAGCGACTAGCTGGCGCAGACTCAGTAATCCGTACGCGCC
    ACTGACTGATTGACGCGAGTTTGCGATGAGAGCAAAACAGCCGATGGGAGATGCCCCTCC
    CACCGGTCGTGACCGTACACGTTATGGACTAGCAAAGTCAACGTTATGGACGAGAGACGA
    TAGATATGTACGCTAGATAGCAATCCAAGATATGCACAGGAGATCCGGTTGGGGCTATCT
    AATTTGCTGGTACCTTATGGCTTTGGAGAGCCTGGCGGGCTGGCTTCGTCTAAGCGCAGA
    AGTACACGAGTGTATGCAGTTTGCAAACCCTAGCCATGGAGTACACGGATGCTTGGAGGA
    GGCAGTACACGGGAGGAGCTCACTCAAGGTAGCAGTTCTGAGTAAGAGAGACGTCTAGTG
    GCCCAATCCAACGATGACACGGGTGAAAAGTCCACTCCCGAGAGGTATAGCTTGACCCTG
    CGGACGTGGTGAGGACAAAGGCAGGCCTACGATCTGGGAAGACGCTCACATTAGATCGAC
    GTCAAATTTTGCTTACCCCGTGTCAAGAAAATCCCTCCACAGTTATTTCAGTACTGCTTA
    GGCGGATGCTCCGGGTACTTTCCTCAGATATTAAACAACATCCAGACTGACCAGACGCCC
    CTAGACTAAAGGACCTGGGTAT
    >Rosalind_3002
    GGCACTCTTTGGCATCAGGGAAGAACCCCCAAACGTGCGGCCGGTGTAGACGCTCGTATG
    GATGCGTAATTGCAGTCCGAGTATATCAATACATTGCGGTGTGATCAACTGCCGAATGAC
    TCCCACCCAAACGCGTTGCAAGAATCGCCGCAAGGGACGACTCAATTACAACCAGACTAC
    GTCCAAAAATCTGAAGATTCTTGCACGCCGGAGCGTTATCTAGTCCGTATGCTCGGGCGT
    TTATCCATACAGCCCCAAAGTTATCAAGCCCAACCAGCCAGGCAGTTGCCCATTACGGGT
    CGGTGGATATTTGCGGTTAATTTTTACATGGAGGGTCACCTTCAATTTTGTTGCAAAGCC
    TGTCTCGCATTCGTTGATTCCGAGAGGTTATCTCATGCAAAAACGGCGGAACTTGACTCC
    TGCTTGGATAGCATGCGGGACTCCATCTCCTTTATCATGTAGCACACGAACGGTAGAATC
    TAAAAGCGGGCCGACGCTGCAATGCCCGCTGGGCCGGGACTAACCTGGTGAGAGCGCCGA
    CTTCGCGATGGACACGACATACTTTTCTATGAGACCCCTCTCGATAATGAAGTCCCGAAC
    CGAACAAAAATCTGCGGCAAATGTGGTGTACCGCCGCGGCCCTCTGTGCCACCCGTAAGA
    AGGTCAACAAAGCGCCCTACGCGAACTCCGCTACTGGTCTAGGCCTATACCCCTAACTGC
    GATGCCCCTAAGCAAATTAGAAGTGTTGCTCTTCACCGCCCTGACTGATCGCCGTAATGT
    CGTATACTGTCCAAGCATCCCGTGGAGCCTAGACGCGCAACTACTCAACTTTCTGGGTTT
    GTCTAATGTCCATGTAGTCCCAGTGTTCACGCCACCCGATACTCGTCTAAT
    >Rosalind_1508
    AGAATTTCTCCTGGGGCTCTATGTGTAGTAGAGAGGCGTATTCCGTTGGTGGGATGATCA
    CACTGCGAGCTGGGAATCTTATGGTGACCACTGGTTTACCCGACTACCCTTATATGACGA
    GGTCACTCCCGCAAACACGTCGTGATAAGGGCCTGGGCCCTTAAATAGATCAGCAGCTTA
    CAGTATGAATTGGTTTCATTTCAGGATAATCTCATGGACAGCCCGAGGCGAACACACCAT
    CGGACCACGCCTCAAACGACGCCAAGCAACAGGGCCAGTTTTAGGGGCCTAGTTCGTCAG
    CGAGCTATAAGATGTGTGGACCTTTTCACTCGATGGCGAGCTGCAATATCCGGAGCACAC
    ACTCTTGGCACGACGGCACACAAGAGTCTTCGACAACGAAATAGCCTCCACAACTCTACC
    GAAATTCATAGCACACTTCTGGGAGAATCCATTTAGACGATGCGAACCCGTTCATCAAGC
    GAGGAGTTTATTTGACCCCCTACATGGCTATCAATAATAGATGGTCGCCTGGACTAATTT
    AGTCTTTAAGAACGTGGTCACCGGTAGGGGACCCGTATGTCAAATGCTACCAGGCGGTAG
    AGGTAACGCCCAACTTAAGTCAGCCCTAACTCTCCTGTGCTCCAGCGGTTTTACCATCCC
    TGACGAGGCGCATCAATGGCCGCGCGCCTCTTCGGGGTTGACGTCAAACGGTCTTGTTAG
    GCTCTATCCTCCGGTCGAATAGTCACCTGATTCCTACATGGCAGTGACGCTACAACAAGT
    TCCATAAATTAGGGCCCAGGCTGACCACCCGAT
    '''
    result = find_max_gc_content(dataset)
    print(*result, sep='\n')