from typing import Dict, List

def parse_fasta(fasta_data: str) -> Dict[str, str]:
    fasta_dict = {}
    strings = fasta_data.strip().split('>')
    
    for string in strings:
        
        if not string:
            continue

        elements = string.split()
        fasta_dict[elements[0]] = ''.join(elements[1:])
    
    return fasta_dict

def get_profile(fasta_data: str) -> Dict[str, List[int]]:
    fasta_dict = parse_fasta(fasta_data)

    profile = {}

    for label, string in fasta_dict.items():
        for index, symbol in enumerate(string):

            if symbol not in profile.keys():
                profile[symbol] = [0] * len(string)

            profile[symbol][index] += 1

    return profile

def get_consensus(profile: Dict[str, List[int]]) -> str:
    consensus = ""
    
    profile_keys = list(profile.keys())
    consensus_length = len(profile[profile_keys[0]])
    
    for index in range(consensus_length):
        most_common_symbol = ('', 0)
        
        for symbol in profile_keys:
            current_symbol = (symbol, profile[symbol][index])
            
            if current_symbol[1] > most_common_symbol[1]:
                most_common_symbol = current_symbol
        
        consensus += most_common_symbol[0]
    
    return consensus

if __name__ == '__main__':
    dataset = '''
    >Rosalind_4038
    TAGCCAAGCCGGTGTAACGAAGGTAGCCATACATACCAACTGTTGGCACATTTCGGCGAC
    GCGATAGGCGAATACATGAAGTCTGTTGTACAACTATGCTGTCATGGCATACTACAGGTG
    TACAGATTTAACAAGCAGAGATGCAAACCCTATGAGACGTGGCCTAATAGTTAAGAAGAC
    TGTGTGAGCCTGCTTGCCCATGTCCGCAGTGAGCCGCTGTAGACACTGGACTGGACCCTA
    ATGCTCCACAAGTGCCTGCCTCAAGGCAAAGGCTGGAAAAATTTTACGAGCAGACTTACG
    CAGAAGTCAGAGACTAAGGCGAGCCTGGTTCGAAGAGAACCGCGGGTTATCTTGTGCGTT
    CGAGTGATCTGAGCATCAGGAGCAGCTGCCAAACACTGTCGACCCAGCACGCCTGCGTCG
    GTTAAGTCCGAGAAATCGGACGGCGTGATTGACCCCAAGGGTCGTCCTCACTAATTGTCA
    ACGAACCTGTCCCGGGTAAATCAGGAAAAGTTGTGTCATCCCAGCTTTCAGGAAAAGTCA
    GTAGCATTTGGATTGCTATCAATCCGATCGCGCAAAGTGTGGAGGCTGCTGATGCGCCGG
    TTCCCCGATTCGATTTATACGGAGGCCCTCGAAATGGACTAAACCAACATCGGCGTGTCA
    GTTCCGCGGTCCTCCCCAGCTGTTCCGCCCCTGTCATTACTAATTATGTAGACTTCCCAG
    TCTGCATCGGACTAAATTCTACGGCTACCATCTACGATCGATGGACCTTAAGAGCGTAAC
    GCATGGAGCTCGGATAATAACGTGTAGTAGTGGTCGAATGATAGGCTAGCAGAGGTATGA
    GTGTGTTATCGTTCGGAGAGCCCCGGCGGGGGTGCCGCGCCTCCGAGGTGAATAGTCACC
    GGCGCGGTAAACTGCCTATA
    >Rosalind_2982
    TGGTAGATGCTACAGAAGAAACGATTTGATTACCACCAATCGTATGAGAATAGTCTCTAT
    CCCGTTGAAGAGGGTACGCACTACAAAGTTGGCCGGACGGATATCAACTAGGTATCATTA
    GCCATAATATTCCCCGAAGCGCACTGCGAAGAGAAGGTTTAACTAGTTAGACGGCCGCCG
    ACTCCCCAATGCAGGTCGGGAAGTTGGCTATGCAGTCCATGACCCATCGACGAGAGGAAT
    CGTCTTCCATCAAGGGTAGGTGTGGGCTGCGATTTCTGTGGGAAAGGATTGGCTCGGTCG
    GCGTTAAGATAAGTAAGGAACCCCTAGGCAATCATGCAGTTCGGATACCAAGCATACCAG
    TTTTTAGTCCTTTCTACGCAGAGGAGTGCTGCAATGTGATGCCACAGTATATTTGGTAGA
    CCGAAAACGTGGGGCAGCTCCTGTATCGTTCCACTGGTGTTTAATATCCTCCTTGCACTG
    AACATGATGAACCAACAGCGTACATGTAACTCCGCGTTAGGGAACTTGAAGCAATTCGTC
    GCTTCGGTATAGTTTCTGGCCAATAAATACAATATACCGGGGGCCCGGCTAATGTTTTGA
    TGTACAATAAATGAATGCCGATTCTAGTATATCAGCGTGCTCACAACGCGGGGTAGAGCC
    AAGCGACAGATTGTAGCGTACATTCCTCGTTCGGACCTGACGACACATGCACACAATGGT
    CGGGTCTTCGCTACCGTTTCTGAGTGCTGACTACGCCAATTTCTACTCGATACTTGGGCC
    CTGGGTGGGGTAGAAGATCGCTGTTCACAGTCTGGATTCTAACCGATTCACGTCCCAGTA
    CTGTCAGTACCTGCTCTTTGAGACGTGAGACGTCCTTGAGACGCCGTTTACGAGCTAGGG
    CATCGCCGGCGTCGAAATTA
    >Rosalind_6250
    CGCTTGTAAACGAAGAAATCCACTAGATTGAACCAGGTCCGAGCCCCATTACCACAATCG
    TCCGTTACAGGTAAGCAATACTGGCTTTTAACGTCCAGTGTCGACTTCCTCTAATACTTG
    CGATGTGTAGCAATCTCCCCCCCAATTTTCCGGAGCGCCTTGGTGTATTTTGACCATAAA
    GTAAGGGCATTTGTCCGCTTCGATAATACATGATACCGTATAGTCAACGCGACCAATAAG
    TTGACTGCCAACAGCACACGGCCGGGACTACGCACTTCCAGGCTGGTAGGGATGAAGCCG
    CCTGGTGAACAGCTGAGCCGGACGATCTTACCTTTTGTACGATGTCGTCCAGGGGTCTCT
    TGCCCATCCGGTAGAGGCATATTCCCACCTGCCACCAGCCATGAGTTCATATAAGTGACT
    CTTAGACATTGATCATCATAGTGACATTAGCCACCCAAACTTCCCCCAGGTCTCGACCAC
    CCATTGGTACGAAAGCCCAAAGCGGGGTCGAGCGTATGAAGGCATTGATGTTCGGTGCCC
    TCGGAAGGGTGGCGGGTCATCTTAGCATTTGTTATTTACGCTCAGATCTTTGTTTGGGCG
    AGAGTACCGGCTCGTCCATCGGAGCTGAGACGCGTATATGTGCAACCGCTTGTGTTAATC
    GCGCACCAGGAAAGCCTCGCGGTACCGGTTTGACCGCGAAAGCACCGACGCGACTTACAG
    AGATGACTCAACTAAATCGATTGAAATCTTAACCACGTCATCGTGCTAACTAGAAAGATT
    TGGACGGGGGGGGCAGCCCAATGTCCTCGCACCTTCCAAGGGCCTATGGCCACGCCTAGA
    ACGCATAGTTCTGCGGCGAACAAATAGCCCGACACGTGTTGAAAAGAAAATAATTAATAC
    CACTGTCAATGCTCACTTCA
    >Rosalind_7213
    CTGCGCAAACGCTCCGAGCCTTCCCATTAATTTGCCCGCCTGTGTTAACCCATGTAACAT
    TTGCGGTAACCCATGCCTTCCCAACCGTCTCTGCCCTCTTTCTGGTGAAAACGTGTACAG
    GCACTCTGCCTTGACGTCGGGTCACCCTATACCGACAGGGTCGATCTTGACCTCCTGAAA
    ATGATACCCCAATGCCAGACATCTGCTCCTATTGTACAAAACTAGGCACGGAGTCTTCAA
    GTAAACTCGTGAACTGTATACAGCCCGTTGTAACCGATCTTTGCGGCCCAACGCCTTCGA
    CGGCGAGGTAGATGTAGACGGTTCGGTAAGCTCGTCAAAGAATGGTCCAGGCTAGCCGAG
    AATACCCTAATGACAGTTCCTAGCTAAGTGATCCGCCTAGACGATCACGCTGAGTTGGTG
    CTTTGTGGGGCCCGCCTTTCCGTAGCCCCACAGCCCACCCTGGGTCAGTCAGCGTTAAAG
    AAGTCGGCTGAGGTCATCGATGCGTCGGAACTCTTTCCCAACTCCAATATAAGCGCTGAT
    AGCTGGTTGCGTGTTCTTTGAAACGACCAGGAAATGAGCTCAGAGGTCGCCGAGCACACT
    ATTCTCGCATGCTGTCCTAAGAATCGGTAATAGCTTTCCAGTCGACTAGTCAGAGATACG
    GGTTAAGGGCAGTTCCTAAGGGTTTTCTAAGACTGGACGACCTAGAGCCACGACTGCCGT
    AAGGTTGATATCTTGCATTTTGATACCGTAGCCAACTATGCAGAATAGATGGAAAATCAT
    GACAATAACTCACGCTCTTCCTACCGCAGATCACTTGAAACAACCACCGACTCTCGCGAT
    AACCTGTCTCATCAATATAAAACCTCGCCCTCACTCGTACAGATGTCTCTAGGAGACCGA
    TCAGGGAATTTTCCGCACGG
    >Rosalind_5073
    GTAGATCTGAAAACCCTATCCACCTGGCAATCGAGGGTAACATTTCGCGCTCGCTGGTGG
    TTAAACCGAGTGTGATCTCGTATGCGCAAGGAAGACGGTGTGTTAGGTCCTAGTTATGAC
    AGTATGAGGTCGGTTTACTCACTTTGTGTTGAACAGAACTCGGGGCGATTACGACTTAGA
    AGTTGCTTACCGCCAGCCAGGTGTTATGCGGAGGCATGTGCCTTAGTTGTCTCATGGATG
    GAGTCTCGCCGGCTTATCTTGGAACTTAGTCACCTGAGTTGGCCAAGGCATACTTAAACG
    AACCATCGGGCTGCAAGCGTAGTGGGCCTCGAGCGGGTCCGCGTAGCCCGTAATACGGAG
    CCGCAGAGTAGAAAGTGGTCTGCTCGTGGGATTACAGTGTCAGCCGTATCTATTACCGGT
    CGGGATCGGGAACGCAGCCTACATTAGGGGGGGAAGCATGACGCTCCGCGCATGAAGTTC
    TGTAACTCTTACGCACAAGTGCAGGTACTACTACAGTGCTCTGCACCTCATGTGGTATTC
    CATTCTCAGACCAAGGTCATGTCTCCTGAAGGGTCCGAATAATTTCTTGTAAACGGGCAA
    TACTTGCTCCCTTTCTTTGGTCCGGAAATTACTTGTACGACCTTGGGAATACTATTGAGA
    ATGTCCAGCTGCAGCTCACATCATTTGTTAATATCAGCGAGCTATGCCTGGAGTAACGAA
    TCTATGTTATACTCAGTGTTGGCATTCCGAGGGGCCACTATATTGAGCGTAGATGCTGCA
    TTGCACAGTTGTCATCCATAAGACGAAGGGTATAGCCGCAGGGGTGAGTCCATGTGGGGT
    TATTTCTCGAGAAAGACAGAGACATTTTCGAGAGCATCCTAGGTTACCAGAGGACATGTG
    TACCCGCATCTAGCTATCAG
    >Rosalind_9880
    CACTTCAAAAGGTGGGCAGAGTTGTACCAGCGGCGGGAACATGCGAGAAGTAGCCAGAGC
    AAAGCTGCCCCGACATCAACTTCAGTTCTCTGAAACAGTAAGCGCTGATGAGCACCCATT
    CGCTTCGCCTACATTCACGGTAACAGTCTCACCTCAGGGTCTACACATTGTAACGCAGCA
    CACCCGACTCTCTCCCCAACCGTCACGGATGAACTTGTTCGTAAGTCCCACCTGTATTTG
    CGTGCGGTCAAAACATTGCCCTTCTACACTAATCCTATTGCAGATAGTCACTAGTGTAGC
    CGCAAGCGACAGTGCTCAGATCGTAGCACGTCCATATATGAATCTGGCGTTTACCATAGA
    CTCCCACCTGCTTTCGAGTCATGACGAGACTGAAAGCACCTCACGCTTTAAGGACGTTTG
    GCTGGGATCTTTACCCCTCTTCCATTAGCATATGGACTACAATGGAAAGTGCTACCGCAA
    AGGAGCTACTGACAATCCCAATGTAACGTTTTGGCGTACCTGGAGACTATGTGGCCGATC
    CAAGCCAGATGCGGGTTAGTTGTCTTGGTATTATTTTTGACTGTTAGTAAGTGACTTTCT
    CCTTAACCGTTAAATAGAAGCACTTGCTATATAGTTCGGAGAATGCTTGATCATAACCGA
    CGTCAACTAAGCGTCTGCGAGGCAGGTATTATCTGACCCAGAACCCAGCAATTACGGAGG
    ACACCATGTACGGGACGTCCCCCACTGGCGCTATAGGATCAATCTGAGTCAATGCGACGA
    CAAGTGTCAATATCGCCTCCTAGAAGCCCCGTGACGTTGCCAGTTATGGGTCTCCTATGT
    GCGCTGCTTCTCCTCGCCAAGTTTAAATGACTTAACGGGGAGCACAATCAACCTGTACTA
    AGAACATAGCTCGCTCAGGA
    >Rosalind_3968
    TATTAAACAGTAGATCGCCGGGATTATCTACGTTGATGTCTGTATGGTTGTAACCAGCAA
    AGGTTACGTGATCTTTTCCAAAAGTTAGTATCCTAAGCGATACGCTCGCACGGCCGGTCG
    GGTCGACAGAAAGTGTACCTGGTTATTGAAGACACATCGCGGCGCCCAAGACTCAAGGTT
    TAATGTATTGATTCCCTCCACTACAACGTTAAAATCAATGCAGCCTTATAGAAGACAGTA
    TTGCGGCGAAGTTACTCTTCGGCGTTCCGAGTTATTGGGGTCGTTCGCGCGTGTCATTAA
    TGGGACCGCATGCTAAAACTCGGTGGATAAAGTATTTGGATCATGACCCATGGAAACCCG
    GTTTAAACTACGTCTGGTTCGGCTTCGTGTCCTACGAGTAGGTTACGAAATGGCCCGGTA
    CGCGGGGGGGGTTGAGCGAAATCGTTCCGCTAGACTGGCGAGTAATACCAACCTTCACCG
    CGTCCTAGTCAAAGCTTGTGTAAGCGGGCCGGACGCTCCCCACCGAAATTTTCCCCTCAT
    CAGGTAAGCAGTCATGGAACGCCGCACCAGTCGAAGGCTGTAGGTCGGGCCCTCAAAGGT
    GGATCTTCATTGCGCTTATCCCTTTAATTATGATCTAGGAATGCTCCTTGCGCTCGAATG
    ATAAAGATAAAGCTGTCCTGGCCGAGAACATACAGCACGACCAGACGCCCCCCTTACAGG
    CTTGGTTGGGGAGATGAAGCTGCACGGAAATCGCTTCTTCCAAACGTCTTCCCAGGGAAG
    TGGTGCACGCGGTTGGCCCTCGACGGGTAGCTCAGTCTGGTGCTGTCTGAGGGCACTTAC
    CTGATCTAAGTAAACAGGGTCGACGTGCGGCACTGATAGTGGAACTCTAAGAATATAATA
    AACTGACTATAGTCTTATAA
    >Rosalind_5365
    CACCTCCGGGCTCTGCGACTCTAACTCCGGTGGCGCAATGCACCATGGCAAATGCCCGAG
    GTCCAACAATATACCTGTCCGGACGCAGCACCTGGGGGAATTCTCAGGCGGTAGCTCAGT
    CGTGTCGTAGCACTACCATCCGTACGCCGAATGCGCCGGTCGCGCACTCGATCAGGTACG
    GTTTTGATAGGCAAAGTGTGGGCAGTCCCGCTTCTATTTTTTCGTTACATTCGTGTAGCG
    TTATCTGTTTCCACGTCCGCGGAACCGATCCGCCTCGAACATTGAAGTTTCGCGATGGGG
    AGCAAACGGGATGCTTGGGGGGAGGTGCAGCTAAGTTATATACGTCCACGAGCCCGGTGT
    GGGTCAAGTTGGAGAGAACAGCAATACGCGATCCTCCCGCGCTGAAACAAGGTTCGAACG
    TTTAGAGTAACACCGAGTTATAAAGAATCATTACTGCCAGGCACTTCCGGTACGCTTCGC
    GGAGTCCACCGATTAAAAGAGAACGTAAGAACTCAGCAATACAAAACTCGTCGCCCCACA
    ATAACCGACTCATACTGTACACCGTAGTTAGCAAGATCGATATCCAGTCCGCCTTGTGCC
    TACTATTGAAGCTGTCCCGACGGCAGCGAGTGTTGTTCCCACGTGAACCTAGCATGTCGT
    GTGACGGTTAAAGGGTAGAACATCCGGAGCAGTCAGCTGACAGCCTCTTCTTGGAGATTT
    TAGTTTGGATAGTTGTCCACTGTCCTACTAGCAGATTCTTAAATTAGCAAGTTCTCTAGA
    TCGTGGTCTCCCACGTGGTGCGGGGCGGGTTAAGTTACCCCATAATTGCGAACGACGGTT
    ACTGCTTACACGGTTGTTCTCTGCCATCCCAGAGGACCCGAATGTAGGCTTTTGACAGTC
    CGACGCAAGACTGTGGACGC
    >Rosalind_2715
    GCCCCTATGAGAAGCAGTAGAGTGGACGTCTGTTGGCCCATGGCCCGAGCTTTCCTTAAG
    CAATAGGTCCTTGTTTGGATCCATCGTTTTTCTTCTAGCAATCCATCGTGTACGGTACGA
    CCCGTCGGGGGCGCTATACGGATGCAACTCATCGAAAACGATCTTCTCTATTGCGGGGAC
    AAAACTTTGTTTTGAACTGCGAGTATATCAACCCGTCGACACGTATCCTAACAGGAAGGG
    ACGAGGCTAGGCGTGTGTATAAAGTGGGTGAAAACGACACGTTACGAAGTTGGATCGATT
    GGACTAGTCTTGAGGATGTATGATTGGATTTAGAGGTCGCATCCTATAGTGCATGTATAT
    TTTCGCATGCGGTGGATGATGCAATCCGGCGATTCCCGATCCGAGTTAGCGTAGGAGGTT
    TCGAATAGGTGAAAAGGCCAAAGCCTCACCAGCTGCGAATAAGGTTCCGTAGGAGGTACT
    TGTAGGAGTTTCCGTAAGAACGCGAAAGTGCTAGCGGCGGCAACAGTCCATTATACTCAA
    AAACACTAAAATACTCACCAAGCTCGCCCGAGTGTCAGATTTGCTCTCAGATCCCGGAAC
    TTGTGGAACCCGTGGCCTGAGCCAAAGGTGCTTTCCGCTTACCCGCGCCTACCGCGCCAG
    CGTAGAGTCGCAATGTTTGGTGGATACGTGTACCGTATCAACGAGCAGGCGCGTGAGAGG
    CGCTGCCGACGGAGCATCCGCTCGGACAGGCCCGGCTGCTTCGGCTCTGCGGACGCTGCG
    TACAGCCCGGTTGCGCTCGTGGCCCAGGGTGATCGGGGCCGTAGCTCCGTCCATAAACAC
    CCAGTTCGTCGTAGTAGAATCGGTACATTAGCTAGCCAAACATTGGAACAGCGACCCTGC
    TTAGTTCACCCAGAATTTTA
    >Rosalind_2236
    TTATGGCAAATATCTCATGACGTTCATTGCAGCTCAATTCAGTGAGAAGCAAAGTGAGTG
    ATTCACTTACAGGAGGAGGAGCCAGTCGTCTCCGATTAATTGGGGCTAGTATGCCCTGGC
    GTATTGTTTCTGTACTGTGTTGGGATGATAGGTCGTTGGCGGGTTCACGTGCCAACTAGC
    CTCGAAACAAAGAGAAGGACCCTATGACGCGTTTTACTGGCACGAGGGCCGTCCATGTAA
    TCCTACCACAACTGAGCTCTAGACGGCTTGTCCTCAGGGCTCAGAATTTCTTAATTTGAG
    TACCCGCCCCTTACTGACAACCTTGATAGGTTCAAAGTATTGTCCTGACGTAATCGCATC
    AGGTAGTTATTATGTTCTCGGAACCGGTGCCCGCAGAAAGCGCTACTAGTAGCCGTATGC
    GAGTTCAAGGCCAAACTAGGCTCCTTGTCGACCTAAGGATTCCGCCGTTACGCGGGCCTC
    GCAGCATGGGACAGCACCGTGGCGCTCAACGATGGCTTCGTTGAAGTGGCTCGAGACGAG
    ATGTTGTGTCGCGCCCCTGGGCACACCAAAAGACGATGTCATAACGTTCATGCTACAACA
    GGGCTAAATTAACCTCGGACTATACGTCGGCCGACCCTCACACACAACCAAATTAACGTT
    ATATCGAGACAAGGTGTGGGCTAGCTACCGAGCGAGCGGATAGCAAGCCATTATGCGGCG
    TACGGCACGGTATAACCACCCGGAGGAGCAACGACCTTCAAGGTCCCTGCCGGCAAGCAG
    TCCTTCAAATTGCGCAGGCAAATAAACTTTAAATGCATATTGTACTTATTGATCGTATTG
    GATGGCAGGAATCGTATGGCTGTCCAGCCATTGAGTCCCGCACACGTTCATGAAACCGGC
    AAGGCTGCCACAACTATTTG
    '''
    profile = get_profile(dataset)
    consensus = get_consensus(profile)
    
    with open('output/problem_cons.txt', mode='w') as output_file:
        print(consensus)
        output_file.write(consensus + '\n')
        
        for symbol in sorted(profile.keys()):
            print('{}:'.format(symbol), *profile[symbol])
            output_file.write('{}: {}\n'.format(symbol, ' '.join(map(str, profile[symbol]))))